### ISSUE TITLE
SIO2-X Leia Home Shelf items for Movies and TV Shows stuck on Random

### ISSUE THREAD

**Issue by ScubyUK** [celadoor/celadoor.github.io#2]
Hi! 

Thanks for getting SIO2-X working on Leia!!

Is there any way of changing the Home Shelf items from Random to Recently Added for Movies and TV Shows?
(Also any way to set TV Shows to display either the episode thumbnail or season poster?)

Thanks again!

Nick

**Comment by celadoor** [comment]
Home Shelf items from Random to Recently Added for Movies and TV Shows - fixed media shelf toggle button.

**Comment by ScubyUK** [comment]
Woah! That was quick!

Works a treat! Thanks!
